# Generated by Django 5.0.6 on 2024-07-10 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_user_birth_date_remove_user_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
